---
title: "thompson-ryan-ADA-homework-4.git"
author: "KRT"
date: "5/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries 

```{r include = FALSE}
library(MASS)
library(tidyverse)
library(dplyr)
library(patchwork) # for plotting
library(scales) # for log y axis scale
library(collapse) # for `fmode()` to find mode
library(BBmisc) # for %nin%
library(devtools)
library(tidycovid19)
library(MuMIn)
library(lme4)
library(lmtest)
library(AICcmodavg)
```

## cv_data data frame

```{r pressure, echo=FALSE}
merged <- download_merged_data(cached = TRUE)
merged <- merged %>%
  group_by(country, iso3c) %>%
  arrange(country, iso3c, date) %>%
  ## new code to replace NAs with zeros
  mutate(
    confirmed = ifelse(is.na(confirmed), 0, confirmed),
    deaths = ifelse(is.na(deaths), 0, deaths),
    recovered = ifelse(is.na(recovered), 0, recovered)
  ) %>%
  ## end of new code
  mutate(
    daily_confirmed = confirmed - lag(confirmed, n = 1),
    daily_deaths = deaths - lag(deaths, n = 1),
    daily_recovered = recovered - lag(recovered, n = 1)
  ) %>%
  mutate(
    daily_confirmed = replace_na(daily_confirmed, 0),
    daily_deaths = replace_na(daily_deaths, 0),
    daily_recovered = replace_na(daily_recovered, 0)
  ) %>%
  ungroup() %>%
  arrange(country, iso3c, date)

add_world1 <- merged %>%
  group_by(date) %>%
  arrange(date) %>%
  summarize(
    country = "World", iso3c = NA,
    confirmed = sum(confirmed, na.rm = TRUE),
    deaths = sum(deaths, na.rm = TRUE),
    recovered = sum(recovered, na.rm = TRUE),
    timestamp = fmode(timestamp)
  ) %>%
  mutate(
    daily_confirmed = confirmed - lag(confirmed, n = 1),
    daily_deaths = deaths - lag(deaths, n = 1),
    daily_recovered = recovered - lag(recovered, n = 1)
  ) %>%
  mutate(
    daily_confirmed = replace_na(daily_confirmed, 0),
    daily_deaths = replace_na(daily_deaths, 0),
    daily_recovered = replace_na(daily_recovered, 0)
  ) %>%
  ungroup() %>%
  arrange(country, iso3c, date)

add_world2 <- merged %>%
  group_by(country, iso3c) %>%
  summarize(
    population = fmode(population),
    land_area_skm = fmode(land_area_skm),
    timestamp = fmode(timestamp)
  ) %>%
  ungroup() %>%
  summarize(
    country = "World", iso3c = NA,
    population = sum(population, na.rm = TRUE),
    land_area_skm = sum(land_area_skm, na.rm = TRUE)
  ) %>%
  mutate(pop_density = population / land_area_skm)

add_world <- left_join(add_world1, add_world2, by = c("country", "iso3c"))
merged <- bind_rows(merged, add_world)

cv_data <- pivot_longer(merged,
  cols = c(
    "confirmed", "deaths", "recovered",
    "daily_confirmed", "daily_deaths", "daily_recovered"
  ),
  names_to = "variable", values_to = "cases"
) %>%
  arrange(country, variable, date) %>%
  rename(area = land_area_skm, density = pop_density) %>%
  mutate(rate = cases / population * 10^6) %>%
  ## new code to omit data before 2020-05-11
  filter(date < "2020-05-11")

cv_summary <- function(d, country_list = "World",
                       plot = TRUE, facet = "country",
                       status = c("confirmed", "deaths", "recovered")) {

  # based on `wes_palettes()` GrandBudapest1, IsleofDogs1, IsleofDogs2
  # from the {wesanderson} package
  my_palette <- c(
    "#5B1A18", "#FD6467", "#F1BB7B", "#D67236",
    "#0F0D0E", "#9986A5", "#79402E", "#CCBA72", "#D9D0D3", "#8D8680",
    "#EAD3BF", "#AA9486", "#B6854D", "#39312F", "#1C1718"
  )

  if (facet == "country") {
    fill <- "variable"
    n <- length(unique(d$variable)) / 2
    # need only half of unique # of variable (3)
  }

  if (facet == "variable") {
    fill <- "country"
    n <- length(country_list)
    # need number of countries
  }

  if ("All" %in% country_list) {
    country_list <- unique(d$country)
    country_list <- setdiff(country_list, "World")
  }

  if ("World" %in% country_list) {
    d <- d %>% filter(country %in% country_list)

    totals <- d %>%
      group_by(variable) %>%
      summarize(
        country = "World",
        cases = max(cases),
        population = max(population),
        area = max(area),
        density = max(density),
        rate = max(rate, na.rm = TRUE),
        on = max(date)
      ) %>%
      select(country, variable, cases, population, area, density, rate, on) %>%
      arrange(variable) %>%
      ungroup()
  }

  if ("World" %nin% country_list) {
    d <- d %>% filter(country %in% country_list)
    totals <- d %>%
      group_by(country, variable) %>%
      summarize(
        cases = max(cases),
        population = max(population),
        area = max(area),
        density = max(density),
        rate = max(rate, na.rm = TRUE),
        on = max(date),
        gdp_capita = fmode(gdp_capita),
        income = fmode(income),
        life_expectancy = fmode(life_expectancy),
        max_sd = max(soc_dist),
        max_mr = max(mov_rest)
      ) %>%
      select(
        country, variable, cases, population, area, density, rate,
        gdp_capita, income, life_expectancy, max_sd, max_mr, on
      ) %>%
      arrange(country, variable) %>%
      ungroup()
  }

  if (plot == TRUE) {
    cc <- filter(d, variable %in% status)
    cum_cases_plot <- ggplot(
      data = cc,
      # use the tidy evaluation pronoun .data to slice the chosen fill
      # variable from the data frame
      aes(
        x = date, y = cases + 1, color = .data[[fill]],
        fill = .data[[fill]]
      )
    ) +
      geom_point(size = 0.5) +
      geom_line() +
      # use the tidy evaluation pronoun .data to slice the chosen facet_wrap
      # variable from the data frame
      facet_wrap(~ .data[[facet]], ncol = 5) +
      xlab("Date") +
      ylab("Log Cumulative Cases") +
      scale_y_log10(
        breaks = trans_breaks("log10", function(x) 10^x),
        labels = trans_format("log10", math_format(10^.x))
      ) +
      scale_color_manual(
        aesthetics = c("color", "fill"),
        name = NULL, values = my_palette
      )

    dc <- filter(d, variable %in% paste0("daily_", status))
    daily_cases_plot <- ggplot(
      data = dc,
      aes(
        x = date, y = cases, color = .data[[fill]],
        fill = .data[[fill]]
      )
    ) +
      geom_point(size = 0.5) +
      geom_line() +
      facet_wrap(~ .data[[facet]], ncol = 5) +
      xlab("Date") +
      ylab("Daily Cases") +
      scale_color_manual(
        aesthetics = c("color", "fill"),
        name = NULL, values = my_palette
      )
  }

  if (plot == TRUE) {
    return(list(
      totals = totals,
      cum_cases_plot = cum_cases_plot,
      daily_cases_plot = daily_cases_plot
    ))
  } else {
    return(list(totals = totals))
  }
}
```

## Challenge 2
```{r}
### Challenge 2
cv_summary(d = cv_data, country_list = c("US", "United Kingdom", 
                                         "Canada", "France", "Germany", 
                                         "Italy", "Japan", "China",
                                         "Russia", "Iran"))

```

## Challenge 3
```{r}
### Challenge 3
d <- cv_summary(d = cv_data, country_list = "All", plot = FALSE)
d <- d[[1]] %>% filter(population > 1000000)
length(unique(d$country))
```

## Challenge 4
```{r}
### Challenge 4
overall <- d %>% filter(variable == "confirmed") %>% arrange(desc(cases))
daily <- d %>% filter(variable == "daily_confirmed") %>% arrange(desc(cases))

head(overall, 10)
head(daily, 10)
```

## Challenge 5
```{r}
### Density
density <- lm(rate ~ density, data = overall)
summary(density)

ggplot(overall, aes(x = density, y = rate)) +
  geom_point() + 
  geom_smooth(formula = y ~ x, method = "lm", se = FALSE)

hist(resid(density))
plot(density, which = 1)
plot(density, which = 2)

overall <- overall %>% mutate(logdensity = log(density), lograte = log(rate + 1))

density <- lm(lograte ~ logdensity, data = overall)
summary(density)

ggplot(overall, aes(x = logdensity, y = lograte)) +
  geom_point() + 
  geom_smooth(formula = y ~ x, method = "lm", se = FALSE)

hist(resid(density))
plot(density, which = 1)
plot(density, which = 2)
plot(density, which = 4)

### Population
population <- lm(rate ~ population, data = overall)
summary(population)

ggplot(overall, aes(x = population, y = rate)) + 
  geom_point() + 
  geom_smooth(formula = y ~ x, method = "lm", se = FALSE)

hist(resid(population))
plot(population, which = 1)
plot(population, which = 2)
plot(population, which = 4)

overall <- overall %>% mutate(logpopulation = log(population))

population <- lm(lograte ~ logpopulation, data = overall)
summary(population)

ggplot(overall, aes(x = logpopulation, y = lograte)) + 
  geom_point() + 
  geom_smooth(formula = y ~ x, method = "lm", se = FALSE)

hist(resid(population))
plot(population, which = 1)
plot(population, which = 2)
plot(population, which = 4)

### GDP
gdp_capita <- lm(rate ~ gdp_capita, data = overall)
summary(gdp_capita)

ggplot(overall, aes(x = gdp_capita, y = rate)) + 
  geom_point() + 
  geom_smooth(formula = y ~ x, method = "lm", se = FALSE)

hist(resid(gdp_capita))
plot(gdp_capita, which = 1)
plot(gdp_capita, which = 2)
plot(gdp_capita, which = 4)

overall <- overall %>% mutate(loggdp_capita = log(gdp_capita))

gdp_capita <- lm(lograte ~ loggdp_capita, data = overall)
summary(gdp_capita)

ggplot(overall, aes(x = loggdp_capita, y = lograte)) + 
  geom_point() + 
  geom_smooth(formula = y ~ x, method = "lm", se = FALSE)

hist(resid(gdp_capita))
plot(gdp_capita, which = 1)
plot(gdp_capita, which = 2)
plot(gdp_capita, which = 4)

### Income
income <- lm(rate ~ income, data = overall)
summary(income)

overall <- overall %>% mutate(income = factor(income,
                                  levels = c("Low income", "Lower middle income", 
                                             "Upper middle income", "High income")))

ggplot(overall, aes(x = income, y = rate)) + 
  geom_boxplot()

hist(resid(income))
plot(income, which = 1)
plot(income, which = 2)
plot(income, which = 4)

income <- lm(lograte ~ income, data = overall)
summary(income)


ggplot(overall, aes(x = income, y = lograte)) + 
  geom_boxplot() 

hist(resid(income))
plot(income, which = 1)
plot(income, which = 2)
plot(income, which = 4)
```

## Challenge 6
```{r}
### Challenge 6

m <- lm(data = overall, lograte ~ logdensity + logpopulation + loggdp_capita + income)
s <- stepAIC(m, scope = . ~ ., direction = "both")
r.squaredGLMM(m)
r.squaredGLMM(s)
```

## Challenge 7
```{r}
### Challenge 7

m <- lm(data = overall, lograte ~ logdensity + loggdp_capita + max_sd + max_mr)
s <- stepAIC(m, scope = . ~ ., direction = "both")
r.squaredGLMM(m)
r.squaredGLMM(s)
```

## Challenge 8
```{r}
new <- cv_data %>% 
  filter(population > 1000000 & variable == "daily_confirmed" & rate > 0)

m1 <- lmer(data = new, rate ~ log(density) + log(gdp_capita) + soc_dist + mov_rest + (1 | country) + (1 | date))
summary(m1)

lme <- lmer(data = new, log(rate) ~ log(density) + log(gdp_capita) + soc_dist + mov_rest + (1 | country) + (1 | date), 
            REML = FALSE)
lme2 <- lmer(data = new, log(rate) ~ log(density) + log(gdp_capita) + soc_dist + (1 | country) + (1 | date), 
             REML = FALSE)
lme3 <- lmer(data = new, log(rate) ~ log(density) + log(gdp_capita) + mov_rest + (1 | country) + (1 | date), 
             REML = FALSE)
summary(lme3)

lme4 <- lmer(data = new, log(rate) ~ log(density) + soc_dist + mov_rest + (1 | country) + (1 | date), 
             REML = FALSE)

lme5 <- lmer(data = new, log(rate) ~ log(gdp_capita) + soc_dist + mov_rest + (1 | country) + (1 | date), 
                  REML = FALSE)

null <- lmer(data = new, log(rate) ~ (1 | country) + (1 | date), REML = FALSE)

aic_table <- aictab(list(lme, lme2, lme3, lme4, lme5, null))
aic_table
```